name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: make environment file
        run: |
          cat<<EOF > .env
          VUE_APP_ODPT_TOKEN=${{ secrets.ODPT_TOKEN }}
          VUE_APP_API_BASE_URL=https://kostl.su8ru.app
          EOF
      - name: cache yarn packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys:
            ${{ runner.os }}-yarn-
      - name: sync submodule
        run: |
          git submodule sync --recursive
          git submodule update
      - name: install
        run: yarn install
      - name: build api
        run: yarn api:build
      - name: build
        run: yarn build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
